### ISSUE TITLE
existsErrorMessageLeadingToReboot function returns always false.

### ISSUE THREAD

**Issue by TakeyaTango** [ARMmbed/mbed-bootloader#13]
existsErrorMessageLeadingToReboot function returns always false.

`
bool existsErrorMessageLeadingToReboot(void)
{
    return false;
}
`

Are you going to implement the contents in the future?
Or does the user need to implement them adapted to the user application?

**Comment by LiyouZhou** [comment]
There is currently no plan to implement this feature. User is welcome to implement this function if needed.

**Comment by TakeyaTango** [comment]
Thank you for your answer.
