### ISSUE TITLE
How is bootCounter incremented?

### ISSUE THREAD

**Issue by TakeyaTango** [ARMmbed/mbed-bootloader#14]
`bootCounter` in main.cpp is the heap variable.
I think that it is reset by rebooting from the user application.
it incremented in `upgradeApplicationFromStorage` function, but i couldn't find such a code that this function is called more than once.

How does this variable increment and reach `MAX_BOOT_RETRIES`?

**Comment by LiyouZhou** [comment]
https://github.com/ARMmbed/mbed-bootloader/blob/1003366bd5db4dfcb3e93bd8a690e6cff7972383/source/upgrade.cpp#L231-L232

as long as the power is not cut, the value in the ram persists(survives soft reboot). If the application successfully bootup the head will get zeroed on libc init.

**Comment by TakeyaTango** [comment]
I tried a soft reset, but `heapVersion` and `bootCounter` were initialized because the following code of the main function was executed.

https://github.com/ARMmbed/mbed-bootloader/blob/1003366bd5db4dfcb3e93bd8a690e6cff7972383/source/main.cpp#L92-L94


Therefore, the condition results for line 219 Below are always true, and `bootCounter` is always be initialized.

https://github.com/ARMmbed/mbed-bootloader/blob/1003366bd5db4dfcb3e93bd8a690e6cff7972383/source/upgrade.cpp#L217-L232

Is my understanding of this correct?

**Comment by TakeyaTango** [comment]
As you said, the variables are uninitialized.
The `heapVersion` uninitialised variable is compared at line 219 in upgrade.cpp.
Is it not necessary to initialize or set before being compared?

https://github.com/ARMmbed/mbed-bootloader/blob/1003366bd5db4dfcb3e93bd8a690e6cff7972383/source/upgrade.cpp#L219

**Comment by LiyouZhou** [comment]
Because they are uninitialised, they will contain the value of whatever was in that memory address before reset. This is now the counter value is able to survive resets.

**Comment by VeijoPesonen** [comment]
I consider this one has been answered. Please reopen if there are still something that needs to be answered.
