### ISSUE TITLE
How do we determine the content of bootloader-details?

### ISSUE THREAD

**Issue by TakeyaTango** [ARMmbed/mbed-bootloader#15]
Some significant values are not set in the `BOOTLOADER_ARM_SOURCE_HASH`, `BOOTLOADER_OEM_SOURCE_HASH` and `BOOTLOADER_STORAGE_LAYOUT`.

Do you plan to implement them in the future?
Does the user need to set some values?
We understand that these values are bootloader-details, but I could not find a document on this definitions.

https://github.com/ARMmbed/mbed-bootloader/blob/061032fd7604e79785152e00175dcfc15dfe06cb/mbed_bootloader_info.h#L24-L34

**Comment by LiyouZhou** [comment]
Thank you for pointing this out, the documentation will be updated to reflect this in the next release.

**Comment by TakeyaTango** [comment]
Thanks for your reply.
