### ISSUE TITLE
Questions for mbed-bootloader

### ISSUE THREAD

**Issue by heejungPark** [ARMmbed/mbed-bootloader#17]
Hi

I'm understanding about bootloader and referring below link.
(https://github.com/ARMmbed/mbed-bootloader)
(https://cloud.mbed.com/docs/current/updating-firmware/bootloaders.html)
(https://cloud.mbed.com/docs/current/porting/porting-the-device-management-update-client.html#bootloader)

I'm confused because could not find the answer or understand about below questions.

1. When a new firmware combined bootloader is initially flashed by drag and drop, is it right that this file is always stored in each active app and bootloader area in internal flash?
2. When we inject the secure information(ex. Device private key and certificate), where is this information stored, internal flash or external flash(SD-card)??

Could you please answer me??

Thanks.

**Comment by LiyouZhou** [comment]
>     1. When a new firmware combined bootloader is initially flashed by drag and drop, is it right that this file is always stored in each active app and bootloader area in internal flash?
> 
When the initial image is built, the tool combines the bootloader, the firmware metadata header and the active firmware image into one binary image. This binary image is copied byte by byte ver Batum onto the internal flash of the device. Hence to answer your question, YES, they are always placed at the correct region on the internal flash.
>     2. When we inject the secure information(ex. Device private key and certificate), where is this information stored, internal flash or an external flash(SD-card)??
> 
In the most common case, the root of trust in written into NVStore. NVStore is like a small file system for internal flash. The RoT is placed in there by the mbed-cloud-client.  Hence to answer your question, Internal flash is where we find the Root of Trust. And the Device private key is derived from the Root of Trust via a key derivation function.
> 
> Could you please answer me??
> 
> Thanks.

**Comment by heejungPark** [comment]
Hi, @LiyouZhou 

Thanks for your kind answer.
I have additional questions.

1. When a image already exists in internal flash, if I copy the another image on the device, How is it work? Is it same?
1. I understood what you said like that the device private key is created on RoT. Actually I try to test Factory provisioning using FCU. In this case, I knew the private key is created by Factory tool(FT). Because I can't think a relation between RoT and FT, I confused a little bit... What am I missing?? Do you have a document to solve this confusion?

Thanks.

**Comment by LiyouZhou** [comment]
>     1. When a image already exists in internal flash, if I copy the another image on the device, How is it work? Is it same? 
Old image will be erased and new image written in its place.
>     2. I understood what you said like that the device private key is created on RoT. Actually, I try to test Factory provisioning using FCU. In this case, I knew the private key is created by Factory tool(FT). Because I can't think a relationship between RoT and FT, I confused a little bit... What am I missing?? Do you have a document to solve this confusion?
- In some places, Device Private key and RoT are used interchangeably. However to be absolutely correct, what is generated in the FCC and stored on the device's internal flash is a Root of trust. What is used to authenticate firmware headers and encrypt off-chip storage is a device private key.

The device private key is derived from the RoT using a key derivation function.

**Comment by heejungPark** [comment]
Okay thanks, @LiyouZhou 

I need to study more about that.
