### ISSUE TITLE
Getting value of "update-client.bootloader-details"

### ISSUE THREAD

**Issue by wajahat-ublox** [ARMmbed/mbed-bootloader#23]
The mbed os pelion example json file requires us to enter the `update-client.bootloader-details` address. The value for this address is taken by running the bootloader binary which shows the following line: 
`[BOOT] Layout: 0 8006F1C`
The value 8006F1C in this case is set in to `update-client.bootloader-details`.

Since latest commit on mbed-bootloader, this information is not displayed any more. One way i can think of is to add a printf myself to get this address but what do you recommend?

Secondly the mbed os pelion example (currently private) is now updated to mbed-os 5.14.0 so do any idea when this repository will be updated to mbed-os 5.14?

Earlier the pelion example test cases were passing mbed-os 5.13.4 and bootloader v4.0.3 but now i am getting failures so just wanted to confirm if there any compatibilty issues with mbed-os 5.14.0 and bootloader version 4.0.3?

@MarceloSalazar

**Comment by wajahat-ublox** [comment]
To answer first part of my question, i now read the  .rodata._ZL10bootloader from map file and use its value in `update-client.bootloader-details ` i hope that's correct way?

**Comment by VeijoPesonen** [comment]
@wajahat-ublox Yes, that's how it's done. [make_release.py](https://github.com/ARMmbed/mbed-bootloader/blob/75a8408cc5f67108c545014bf6d605493e683efb/scripts/make_release.py#L235)

**Comment by wajahat-ublox** [comment]
@VeijoPesonen Thanks but readme of both mbed-bootloader and mbed-os-example-pelion need to be updated for this information.

**Comment by VeijoPesonen** [comment]
Ok, I'll update the README.md.
