### ISSUE TITLE
Update instructions to benefit from `mbed dm` feature

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-bootloader#6]
Mbed OS 5.10 (about to be released) supports merging the application with the bootloader automatically.
Requires having Mbed CLI 1.8.x

Instructions on this mbed-bootloader repo should be updated:
https://github.com/ARMmbed/mbed-bootloader#build-instructions

An include references to documentation, for example:
- Mbed CLI
  https://os.mbed.com/docs/latest/tools/cli-update.html (to be made available asap)
- Create an application include a bootloader
https://os.mbed.com/docs/latest/tutorials/bootloader.html (to be made available asap)

@LiyouZhou is this something you could help with?

**Comment by LiyouZhou** [comment]
This functionality is relevant to the mbed-cloud-client-example repo but not so much relevant to this bootloader source code.

**Comment by MarceloSalazar** [comment]
People don't necessarily need to use the mbed-cloud-client-example repo.
I'm just suggesting to update links to point at the docs in the web ;-)

**Comment by MarceloSalazar** [comment]
I try to raise a ticket, but feel a simple PR will resolve this.

Additional note (as per Partner feedback), we need to remove references to `combine_bootloader_with_app.py`, as it's no longer recommended when working with Mbed OS 5.10+

**Comment by MarceloSalazar** [comment]
Internal reference: [IOTUPD-3426](https://jira.arm.com/browse/IOTUPD-3426)

**Comment by VeijoPesonen** [comment]
Instructions have been added.
