### ISSUE TITLE
Mbed OS PR #12278 breaks compilation

### ISSUE THREAD

**Issue by marcuschangarm** [ARMmbed/mbed-bootloader#60]
Mbed OS renamed `target.default_lib` to `target.c_lib` in PR https://github.com/ARMmbed/mbed-os/pull/12278 which breaks the current configuration files.

@SeppoTakalo I would recommend pinning Mbed OS to a version to your liking.

**Comment by SeppoTakalo** [comment]
Fixed in https://github.com/ARMmbed/mbed-bootloader/pull/61

So master branch works against Mbed OS master. Release branch work against 5.15 release.
