### ISSUE TITLE
bootloader readme.md refers to internal repository

### ISSUE THREAD

**Issue by jygeARM** [ARMmbed/mbed-bootloader#7]
The README.md has this about Device Secret Key:

> Alternatively you can choose to use a custom device specific RoT by implementing the function mbed_cloud_client_get_rot_128bit. An example can be found here.

The _here_ points to mbed-bootloader-internal repository which is not accessible by the same audience as mbed-bootloader.

**Comment by LiyouZhou** [comment]
fixed in https://github.com/ARMmbed/mbed-bootloader/commit/74e94f04265a4336d139e7c4fedbc3569d12e587
