### ISSUE TITLE
Library name 'sd' is not unique

### ISSUE THREAD

**Issue by jygeARM** [ARMmbed/mbed-bootloader#8]
The upcoming 5.10 has new SD block device and the existing sd-driver conflicts with it.
Ref: https://github.com/ARMmbed/mbed-os/pull/7774

**Comment by JanneKiiskila** [comment]
Yep, this repo is not (yet) updated to work with Mbed OS 5.10.

**Comment by LiyouZhou** [comment]
Please see new release version 3.5.0 which is integrated with mbed-os 5.10
