### ISSUE TITLE
Need better information on how to configure nvstore

### ISSUE THREAD

**Issue by jygeARM** [ARMmbed/mbed-bootloader#9]
Building for K64F with 5.10 rc, ends up in error:

> Building project mbed-bootloader (K64F, GCC_ARM)
> Scan: mbed-bootloader
> Scan: env
> [ERROR] Attempt to override undefined parameter 'nvstore.area_1_address' in 'application[K64F]'
> 

Not able to find documentation on how to actually configure my build correctly.

**Comment by davidsaada** [comment]
@jygeARM Will move over the Handbook and README to see where this can be improved.
In the meantime, a good example to what you want to do can be found in the [NVStore example repo](https://github.com/ARMmbed/mbed-os-example-nvstore). The [K64F config file with 8KB areas](https://github.com/ARMmbed/mbed-os-example-nvstore/blob/master/mbed_app-K64F-8KB-areas.json) shows exactly what to do here.

**Comment by davidsaada** [comment]
Oh, just missed the fact that it's under bootloader and not under mbed-os. I think the config options are the same, at least looking at its [mbed_app.json file](https://github.com/ARMmbed/mbed-bootloader/blob/master/mbed_app.json), but maybe I'm missing something here.
@LiyouZhou can you help?

**Comment by ashok-rao** [comment]
I can reproduce this as well.. 
```
C:\Ashok\mbed_CLI\OoB_5_10\BL\mbed-bootloader>mbed compile -t ARM -m K64F
Building project mbed-bootloader (K64F, ARM)
Scan: mbed-bootloader
Scan: env
[ERROR] Attempt to override undefined parameter 'nvstore.area_1_address' in 'application[K64F]'
[mbed] ERROR: "c:\python27\python.exe" returned error.
       Code: 1
       Path: "C:\Ashok\mbed_CLI\OoB_5_10\BL\mbed-bootloader"
       Command: "c:\python27\python.exe -u C:\Ashok\mbed_CLI\OoB_5_10\BL\mbed-bootloader\mbed-os\tools\make.py -t ARM -m K64F --source . --build .\BUILD\K64F\ARM"
       Tip: You could retry the last command with "-v" flag for verbose output
---
```
```
C:\Ashok\mbed_CLI\OoB_5_10\BL\mbed-bootloader>mbed ls
mbed-bootloader (#1003366bd5db, tag: v3.4.0)
|- mbed-cloud-client (#9b0bc6a2f3f1, tag: 1.4.0)
|- mbed-os (#610e35ddc6d5, tag: mbed-os-5.10.0-rc3)
|- minimal-printf (#5cbf9d1dcb58)
`- sd-driver (#ae7e7440054c, tag: sd-driver-0.1.2-mbed-os-5.6.1)
```

cc @MarceloSalazar

**Comment by LiyouZhou** [comment]
please see new release 3.5.0 which is integrated with mbed-so 5.10.
